Importing Libreries

In [1]:
import pandas as pd 
import tensorflow as tf 
import matplotlib.pyplot as plt 
import seaborn as sns

Data Preprocessing 

In [2]:
#Training image preprocessing 
training_set = tf.keras.utils.image_dataset_from_directory(
    '../Plant Disease data/train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    format="tf",
    verbose=True,
)

Found 70295 files belonging to 38 classes.


In [3]:
#Validation image procsssing 

validation_set = tf.keras.utils.image_dataset_from_directory(
    '../Plant Disease data/valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    format="tf",
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [4]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [5]:
for x,y in training_set: 
    print(x, x.shape)
    print(y, y.shape)
    break

tf.Tensor(
[[[[168.5  148.5  139.5 ]
   [174.25 154.25 145.25]
   [184.5  164.5  155.5 ]
   ...
   [147.75 124.75 110.75]
   [139.25 116.25 102.25]
   [144.25 121.25 107.25]]

  [[177.   157.   148.  ]
   [150.75 130.75 121.75]
   [186.   166.   157.  ]
   ...
   [145.5  122.5  108.5 ]
   [145.75 122.75 108.75]
   [136.75 113.75  99.75]]

  [[165.75 145.75 136.75]
   [166.25 146.25 137.25]
   [162.   142.   133.  ]
   ...
   [147.75 124.75 110.75]
   [124.   101.    87.  ]
   [133.   110.    96.  ]]

  ...

  [[154.25 132.25 118.25]
   [170.5  148.5  134.5 ]
   [158.25 136.25 122.25]
   ...
   [132.5  106.5   91.5 ]
   [134.75 108.75  93.75]
   [143.   117.   102.  ]]

  [[165.25 143.25 129.25]
   [162.   140.   126.  ]
   [163.   141.   127.  ]
   ...
   [134.75 108.75  93.75]
   [129.25 103.25  88.25]
   [132.75 106.75  91.75]]

  [[167.25 145.25 131.25]
   [168.5  146.5  132.5 ]
   [154.25 132.25 118.25]
   ...
   [128.   102.    87.  ]
   [134.5  108.5   93.5 ]
   [136.5  110.5   9

Model Building

To avoid overshooting 
1. Choose small Learnig rate default 0.001 we are taking 0.0001
1. There may be chance of underfitting, so increase number of neuron 
3. Add more convolution layer to extract more feature from images there may be posibility that module unable to capture relevant feature or module is confusing due to lack of feature so feed with more feature


In [6]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPool2D , Flatten, Dropout
from tensorflow.keras.models import Sequential

In [7]:
model = Sequential() 

In [8]:
#Building Convolution Layers 

model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu', input_shape = [128, 128,3]))
model.add(Conv2D(filters=32, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

C:\Users\moham\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
#Building Convolution Layers 

model.add(Conv2D(filters=64, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=64, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [10]:
#Building Convolution Layers 

model.add(Conv2D(filters=128, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=128, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [11]:
#Building Convolution Layers 

model.add(Conv2D(filters=256, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=256, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [12]:
#Building Convolution Layers 

model.add(Conv2D(filters=512, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=512, kernel_size=3, activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

In [13]:
model.add(Dropout(0.25))

In [14]:
model.add(Flatten())

In [15]:
model.add(Dense(units=1500, activation='relu'))

In [16]:
model.add(Dropout(0.4)) #To avoid overfitting 

In [17]:
#Output Layer
model.add(Dense(units=38, activation='softmax'))

Compiling Model

In [18]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

In [19]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        57,038 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
training_history = model.fit(x=training_set, validation_data=validation_set, epochs=10)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 3507s 2s/step - accuracy: 0.6110 - loss: 1.3118 - val_accuracy: 0.8451 - val_loss: 0.4816
Epoch 2/10
1626/2197 ━━━━━━━━━━━━━━━━━━━━ 14:15 1s/step - accuracy: 0.8348 - loss: 0.5338

#Model Evaluation

In [ ]:
#Model Evaluation on Training Set
train_loss, train_acc = model.evaluate(training_set)

In [ ]:
print(train_loss, train_acc)

In [ ]:
#Model Evaluation on Validation set 
val_loss, val_acc = model.evaluate(validation_set)

In [ ]:
print(val_loss, val_acc)

Saving Model

In [ ]:
model.save("trained_model.keras")

In [ ]:
training_history.history

In [ ]:
#Recording History on JSON 
import json 
with open("training_hist.json", "w") as f: 
    json.dump(training_history.history, f)

Accuracy Visualization 

In [ ]:
epochs = [i for i in range(1,11)]
plt.plot(epochs, training_history['accuracy'], color = 'red', label='Training Accuracy')
plt.plot(epochs, training_history['val_accuracy'], color = 'blue', label='Validation Accuracy')
plt.xlabel("No. of Epochs")
plt.ylabel("Accuracy Result")
plt.title("Visualization of Accuracy Result")
plt.legend()
plt.show() 